//ConfigActions
export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';

//MoviesAction
export const SET_UPCOMING_MOVIES = 'SET_UPCOMING_MOVIES';
export const SET_POPULAR_MOVIES = 'SET_POPULAR_MOVIES';
export const SET_TOP_RATED_MOVIES = 'SET_TOP_RATED_MOVIES';
export const SET_GENRES_MOVIES = 'SET_GENRES_MOVIES';
export const SET_CREDITS_MOVIES = 'SET_CREDITS_MOVIES';
